/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author USUARIO
 */
public class FormularioMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormularioMenu
     */
    public FormularioMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cargos = new javax.swing.JButton();
        btn_autor = new javax.swing.JButton();
        btn_categoria = new javax.swing.JButton();
        btn_devoluciones = new javax.swing.JButton();
        btn_editorial = new javax.swing.JButton();
        btn_ejemplares = new javax.swing.JButton();
        btn_empleados = new javax.swing.JButton();
        btn_libros = new javax.swing.JButton();
        btn_autores = new javax.swing.JButton();
        btn_Prestamo = new javax.swing.JButton();
        btn_TipoUsuario = new javax.swing.JButton();
        btn_usuario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_cargos.setText("Cargos");
        btn_cargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargosActionPerformed(evt);
            }
        });

        btn_autor.setText("Autores");
        btn_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_autorActionPerformed(evt);
            }
        });

        btn_categoria.setText("Categoria");
        btn_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_categoriaActionPerformed(evt);
            }
        });

        btn_devoluciones.setText("Devoluciones");
        btn_devoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_devolucionesActionPerformed(evt);
            }
        });

        btn_editorial.setText("Editorial");
        btn_editorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editorialActionPerformed(evt);
            }
        });

        btn_ejemplares.setText("Ejemplares");
        btn_ejemplares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ejemplaresActionPerformed(evt);
            }
        });

        btn_empleados.setText("Empleados");
        btn_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empleadosActionPerformed(evt);
            }
        });

        btn_libros.setText("Libros");
        btn_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_librosActionPerformed(evt);
            }
        });

        btn_autores.setText("Autores de los Libros");
        btn_autores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_autoresActionPerformed(evt);
            }
        });

        btn_Prestamo.setText("Libros Prestados");
        btn_Prestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrestamoActionPerformed(evt);
            }
        });

        btn_TipoUsuario.setText("Tipos de Usuarios");
        btn_TipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TipoUsuarioActionPerformed(evt);
            }
        });

        btn_usuario.setText("Usuarios");
        btn_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuarioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Bibloteca UTH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_editorial)
                            .addComponent(btn_cargos)
                            .addComponent(btn_autores))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_autor)
                                    .addComponent(btn_ejemplares))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_empleados)
                                    .addComponent(btn_categoria))
                                .addGap(54, 54, 54))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Prestamo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_TipoUsuario)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_usuario)
                            .addComponent(btn_libros)
                            .addComponent(btn_devoluciones))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_autor)
                    .addComponent(btn_categoria)
                    .addComponent(btn_devoluciones)
                    .addComponent(btn_cargos))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_editorial)
                    .addComponent(btn_ejemplares)
                    .addComponent(btn_empleados)
                    .addComponent(btn_libros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_autores)
                    .addComponent(btn_Prestamo)
                    .addComponent(btn_TipoUsuario)
                    .addComponent(btn_usuario))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargosActionPerformed
        // TODO add your handling code here:
        ListadoCargos form = new ListadoCargos();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cargosActionPerformed

    private void btn_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_autorActionPerformed
        // TODO add your handling code here:
        ListadoAutor form = new ListadoAutor();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_autorActionPerformed

    private void btn_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_categoriaActionPerformed
        // TODO add your handling code here:
        ListadoCategorias form = new ListadoCategorias();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_categoriaActionPerformed

    private void btn_devolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_devolucionesActionPerformed
        // TODO add your handling code here:
        ListadoDevoluciones form = new ListadoDevoluciones();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_devolucionesActionPerformed

    private void btn_editorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editorialActionPerformed
        // TODO add your handling code here:
        ListadoEditorial form = new ListadoEditorial();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_editorialActionPerformed

    private void btn_ejemplaresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ejemplaresActionPerformed
        // TODO add your handling code here:
        ListadoEjemplares form = new ListadoEjemplares();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_ejemplaresActionPerformed

    private void btn_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empleadosActionPerformed
        // TODO add your handling code here:
        ListadoEmpleado form = new ListadoEmpleado();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_empleadosActionPerformed

    private void btn_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_librosActionPerformed
        // TODO add your handling code here:
        ListadoLibros form = new ListadoLibros();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_librosActionPerformed

    private void btn_autoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_autoresActionPerformed
        // TODO add your handling code here:
        ListadoLibrosAutores form = new ListadoLibrosAutores();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_autoresActionPerformed

    private void btn_PrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrestamoActionPerformed
        // TODO add your handling code here:
        ListadoPrestamos form = new ListadoPrestamos();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_PrestamoActionPerformed

    private void btn_TipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TipoUsuarioActionPerformed
        // TODO add your handling code here:
        ListadoTipoUsuario form = new ListadoTipoUsuario();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_TipoUsuarioActionPerformed

    private void btn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuarioActionPerformed
        // TODO add your handling code here:
        ListadoUsuarios form = new ListadoUsuarios();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Prestamo;
    private javax.swing.JButton btn_TipoUsuario;
    private javax.swing.JButton btn_autor;
    private javax.swing.JButton btn_autores;
    private javax.swing.JButton btn_cargos;
    private javax.swing.JButton btn_categoria;
    private javax.swing.JButton btn_devoluciones;
    private javax.swing.JButton btn_editorial;
    private javax.swing.JButton btn_ejemplares;
    private javax.swing.JButton btn_empleados;
    private javax.swing.JButton btn_libros;
    private javax.swing.JButton btn_usuario;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
