package View;

import Controller.EmpleadosDAO;
import Model.CargoComboItem;
import Model.Empleados;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;


public class FormularioEmpleado extends javax.swing.JDialog {

    private JComboBox<CargoComboItem> cmbCargo;
    private String Mode;
    private int id;
    private EmpleadosDAO dao = new EmpleadosDAO();
    private ListadoEmpleado parent;
    
    public FormularioEmpleado(ListadoEmpleado pParent, boolean modal, String pMode, int pId) {
        super(pParent, modal);
        this.parent = pParent;
        this.Mode = pMode;
        this.id = pId;
        initComponents();
        
        cmbCargo = new JComboBox<>();
        cmbCargo.setBounds(200, 200, 200, 25); // ajusta posición/tamaño según tu diseño
        add(cmbCargo);
        cargarCargos();
        
        txt_id.setText(String.valueOf(pId));
        txt_id.setEnabled(false);

        if (Mode.equals("INS")) {
            btn_accion.setText("Insertar");
        } else {
            Empleados empleado = dao.buscarPorId(id);
            if (empleado != null) {
                txt_id.setText(String.valueOf(empleado.getEmpleadoID()));
                txt_nombre.setText(empleado.getNombre());
                txt_apellido.setText(empleado.getApellido());
                txt_telefono.setText(empleado.getTelefono());

                // Seleccionar en el combo el cargo correspondiente
                for (int i = 0; i < cmbCargo.getItemCount(); i++) {
                    CargoComboItem item = cmbCargo.getItemAt(i);
                    if (item.getId() == empleado.getCargosID()) {
                        cmbCargo.setSelectedIndex(i);
                        break;
                    }
                }

                if (Mode.equals("UPD")) {
                    btn_accion.setText("Actualizar");
                } else if (Mode.equals("DLT")) {
                    txt_nombre.setEditable(false);
                    txt_apellido.setEditable(false);
                    txt_telefono.setEditable(false);
                    cmbCargo.setEnabled(false);
                    btn_accion.setText("Eliminar");
                }
            }
        }
    }
    
    private void cargarCargos() {
    List<CargoComboItem> cargos = dao.obtenerCargosParaCombo();
    cmbCargo.removeAllItems();

    for (CargoComboItem item : cargos) {
        cmbCargo.addItem(item);
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_id = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_apellido = new javax.swing.JLabel();
        lbl_cargo = new javax.swing.JLabel();
        lbl_telefono = new javax.swing.JLabel();
        btn_accion = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_id.setText("ID:");

        lbl_nombre.setText("Nombre:");

        lbl_apellido.setText("Apellido:");

        lbl_cargo.setText("Cargo:");

        lbl_telefono.setText("Telefono:");

        btn_accion.setText("Insertar");
        btn_accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accionActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btn_accion)
                        .addGap(94, 94, 94)
                        .addComponent(btn_salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_cargo)
                            .addComponent(lbl_apellido)
                            .addComponent(lbl_telefono)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_id)
                                .addComponent(lbl_nombre)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_apellido)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(lbl_cargo)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefono)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_accion)
                    .addComponent(btn_salir))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_accionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accionActionPerformed
        // TODO add your handling code here:
        if (Mode.equals("INS")) {
            try {
                String nombre = txt_nombre.getText().trim();
                String apellido = txt_apellido.getText().trim();
                String telefono = txt_telefono.getText().trim();
                CargoComboItem cargoSeleccionado = (CargoComboItem) cmbCargo.getSelectedItem();

                if (nombre.isEmpty() || apellido.isEmpty() || telefono.isEmpty() || cargoSeleccionado == null) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar nombre, apellido y seleccionar un cargo.");
                    return;
                }

                Empleados nuevoEmpleado = new Empleados();
                nuevoEmpleado.setNombre(nombre);
                nuevoEmpleado.setApellido(apellido);
                nuevoEmpleado.setTelefono(telefono);
                nuevoEmpleado.setCargosID(cargoSeleccionado.getId());

                if (dao.insert(nuevoEmpleado)) {
                    JOptionPane.showMessageDialog(this, "Empleado insertado correctamente.");
                    parent.refrescarInfo();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo insertar el empleado.");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al insertar: " + e.getMessage());
            }
        }

        if (Mode.equals("UPD")) {
            try {
                String nombre = txt_nombre.getText().trim();
                String apellido = txt_apellido.getText().trim();
                String telefono = txt_telefono.getText().trim();
                CargoComboItem cargoSeleccionado = (CargoComboItem) cmbCargo.getSelectedItem();

                if (nombre.isEmpty() || apellido.isEmpty() || telefono.isEmpty() || cargoSeleccionado == null) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar nombre, apellido y seleccionar un cargo.");
                    return;
                }

                Empleados empleadoActualizado = new Empleados();
                empleadoActualizado.setEmpleadoID(id);
                empleadoActualizado.setNombre(nombre);
                empleadoActualizado.setApellido(apellido);
                empleadoActualizado.setTelefono(telefono);
                empleadoActualizado.setCargosID(cargoSeleccionado.getId());

                if (dao.update(empleadoActualizado)) {
                    JOptionPane.showMessageDialog(this, "Empleado actualizado correctamente.");
                    parent.refrescarInfo();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo actualizar el empleado.");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
            }
        }

        if (Mode.equals("DLT")) {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Deseas eliminar este empleado?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                boolean eliminado = dao.delete(id);

                if (eliminado) {
                    JOptionPane.showMessageDialog(this, "Empleado eliminado correctamente.");
                    parent.refrescarInfo();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar el empleado.");
                }
            }
        }
    }//GEN-LAST:event_btn_accionActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioEmpleado dialog = new FormularioEmpleado(new ListadoEmpleado(), true,"INS",0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accion;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel lbl_apellido;
    private javax.swing.JLabel lbl_cargo;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
