package View;

import Controller.CategoriaDAO;
import Model.Categorias;
import javax.swing.JOptionPane;


public class FormularioCategorias extends javax.swing.JDialog {
    
    private String Mode;
    private int id;
    private CategoriaDAO dao = new CategoriaDAO();
    private ListadoCategorias parent;

    public FormularioCategorias(ListadoCategorias pParent, boolean modal, String pMode, int pId) {
        super(pParent, modal);
        this.parent = pParent;
        initComponents();
        this.Mode = pMode;
        this.id = pId;
        
        txt_id.setText(String.valueOf(pId));
        txt_id.setEnabled(false);

        if (Mode.equals("INS")) {
             btn_Accion.setText("Insertar");
        } else {
            Categorias cat = dao.buscarPorId(id);
            if (cat != null) {
                txt_id.setText(String.valueOf(cat.getId()));
                txt_descripcion.setText(cat.getDescripcion());

                if (Mode.equals("UPD")) {
                     btn_Accion.setText("Actualizar");
                } else if (Mode.equals("DLT")) {
                    txt_descripcion.setEditable(false);
                    btn_Accion.setText("Eliminar");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_id = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        btn_Accion = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_id.setText("ID:");

        lbl_descripcion.setText("Descripción:");

        btn_Accion.setText("Insertar");
        btn_Accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccionActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Accion)
                        .addGap(84, 84, 84)
                        .addComponent(btn_salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_id)
                            .addComponent(lbl_descripcion))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_descripcion)
                    .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Accion)
                    .addComponent(btn_salir))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_AccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccionActionPerformed
        // TODO add your handling code here:
        if (Mode.equals("INS")) {
            try {
                String descripcion = txt_descripcion.getText().trim();

                if (descripcion.isEmpty()) {
                 JOptionPane.showMessageDialog(this, "Debe ingresar una descripción.");
                    return;
                }

                Categorias nuevaCategoria = new Categorias(0, descripcion);

                if (dao.insertarCategoria(nuevaCategoria)) {
                    JOptionPane.showMessageDialog(this, "Categoría insertada correctamente.");
                    parent.refrescarInfo();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo insertar la categoría.");
                }   
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al insertar: " + e.getMessage());
            }
        }

        if (Mode.equals("UPD")) {
            try {
                String descripcion = txt_descripcion.getText().trim();

                if (descripcion.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe ingresar una descripción.");
                    return;
                }

                Categorias categoriaActualizada = new Categorias(id, descripcion);

                if (dao.actualizarCategoria(categoriaActualizada)) {
                    JOptionPane.showMessageDialog(this, "Categoría actualizada correctamente.");
                    parent.refrescarInfo();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo actualizar la categoría.");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
            }
        }

        if (Mode.equals("DLT")) {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Deseas eliminar esta categoría?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                boolean eliminado = dao.eliminarCategoria(id);

                if (eliminado) {
                    JOptionPane.showMessageDialog(this, "Categoría eliminada correctamente.");
                    parent.refrescarInfo();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar la categoría.");
                }
            }
        }    
    }//GEN-LAST:event_btn_AccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioCategorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioCategorias dialog = new FormularioCategorias(new ListadoCategorias(), true,"INS",0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Accion;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
